# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        MainWindow.setMinimumSize(QtCore.QSize(800, 400))
        MainWindow.setMaximumSize(QtCore.QSize(800, 400))
        MainWindow.setStyleSheet("background-color: rgb(80,80,80)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_menu_label = QtWidgets.QLabel(self.centralwidget)
        self.main_menu_label.setGeometry(QtCore.QRect(190, 10, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.main_menu_label.setFont(font)
        self.main_menu_label.setStyleSheet("color: rgb(255,255,255)")
        self.main_menu_label.setIndent(95)
        self.main_menu_label.setObjectName("main_menu_label")
        self.menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.menu_button.setGeometry(QtCore.QRect(190, 210, 141, 51))
        self.menu_button.setStyleSheet("background-color: rgb(150,150,150)\n"
"")
        self.menu_button.setObjectName("menu_button")
        self.quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button.setGeometry(QtCore.QRect(460, 210, 141, 51))
        self.quit_button.setStyleSheet("background-color: rgb(150,150,150)")
        self.quit_button.setObjectName("quit_button")
        self.cookie_label = QtWidgets.QLabel(self.centralwidget)
        self.cookie_label.setGeometry(QtCore.QRect(40, 66, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cookie_label.setFont(font)
        self.cookie_label.setStyleSheet("color: rgb(255,255,255)")
        self.cookie_label.setObjectName("cookie_label")
        self.sandwich_label = QtWidgets.QLabel(self.centralwidget)
        self.sandwich_label.setGeometry(QtCore.QRect(40, 138, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sandwich_label.setFont(font)
        self.sandwich_label.setStyleSheet("color: rgb(255,255,255)")
        self.sandwich_label.setObjectName("sandwich_label")
        self.water_label = QtWidgets.QLabel(self.centralwidget)
        self.water_label.setGeometry(QtCore.QRect(40, 206, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.water_label.setFont(font)
        self.water_label.setStyleSheet("color: rgb(255,255,255)")
        self.water_label.setObjectName("water_label")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(140, 280, 141, 51))
        self.add_button.setStyleSheet("background-color: rgb(150,150,150)")
        self.add_button.setObjectName("add_button")
        self.done_button = QtWidgets.QPushButton(self.centralwidget)
        self.done_button.setGeometry(QtCore.QRect(510, 280, 141, 51))
        self.done_button.setStyleSheet("background-color: rgb(150,150,150)")
        self.done_button.setObjectName("done_button")
        self.receipt_label = QtWidgets.QLabel(self.centralwidget)
        self.receipt_label.setGeometry(QtCore.QRect(440, 60, 241, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.receipt_label.setFont(font)
        self.receipt_label.setStyleSheet("qproperty-alignment: AlignTop;\n"
"color: rgb(255,255,255)")
        self.receipt_label.setText("")
        self.receipt_label.setObjectName("receipt_label")
        self.cookie_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.cookie_entry.setGeometry(QtCore.QRect(140, 60, 104, 31))
        self.cookie_entry.setStyleSheet("color: rgb(255,255,255)")
        self.cookie_entry.setObjectName("cookie_entry")
        self.sandwich_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.sandwich_entry.setGeometry(QtCore.QRect(140, 130, 104, 31))
        self.sandwich_entry.setStyleSheet("color: rgb(255,255,255)")
        self.sandwich_entry.setObjectName("sandwich_entry")
        self.water_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.water_entry.setGeometry(QtCore.QRect(140, 200, 104, 31))
        self.water_entry.setStyleSheet("color: rgb(255,255,255)")
        self.water_entry.setObjectName("water_entry")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(280, 40, 172, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: rgb(255,255,255)")
        self.error_label.setObjectName("error_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Keaghon\'s Diner"))
        self.main_menu_label.setText(_translate("MainWindow", "Keaghon\'s Diner"))
        self.menu_button.setText(_translate("MainWindow", "Menu"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.cookie_label.setText(_translate("MainWindow", "Cookie"))
        self.sandwich_label.setText(_translate("MainWindow", "Sandwich"))
        self.water_label.setText(_translate("MainWindow", "Water"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.done_button.setText(_translate("MainWindow", "Done"))
        self.error_label.setText(_translate("MainWindow", "Please enter a valid number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
